version: 0.14.40
apiVersion: v1
appVersion: 3.4.9
name: jupyter
description: Jupyter
home: https://jupyter.org/
icon: https://jupyter.org/assets/nav_logo.svg
sources:
  - https://github.com/jupyter
maintainers:
  - name: bivas
    email: eliranb@iguazio.com
