apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlrun.db.fullname" . }}
  labels:
    {{- include "mlrun.db.labels" . | nindent 4 }}
data:
  dsn: {{ include "mlrun.dsn" . | b64enc }}
  oldDsn: {{ toYaml .Values.httpDB.oldDsn | b64enc }}
