{{- if .Values.controller.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "provazio.controller.name" . }}
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller

{{- if has "IguazioTenant" .Values.controller.crd.kinds }}
---
# If the controller is enabled and responsible for IguazioTenantAppServiceSet, it will need the ability
# to create resources like ingressess, secrets, etc. Things that are not created by the service
# helm charts which are under the namespace's tiller service account. This creates a ClusterRole
# granting namespaced permission to these resources (to be used by each managed namespace)

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "provazio.controller.name" . }}-namespace-admin
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "provazio.controller.name" . }}-admission-admin
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
{{- end }}


{{- if has "IguazioTenantAppServiceSet" .Values.controller.crd.kinds }}
---
# If the controller is enabled and responsible for IguazioTenantAppServiceSet, bind to the cluster role 
# allowing access to IguazioTenantAppServiceSet CRD to the controller's service account

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "provazio.controller.name" . }}-iguaziotenantappserviceset-crd-admin
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
subjects:
- kind: ServiceAccount
  name: {{ template "provazio.controller.name" . }}
roleRef:
  kind: ClusterRole
  name: iguaziotenantappserviceset-crd-admin
  apiGroup: rbac.authorization.k8s.io

{{- end }}

{{- if has "IguazioTenant" .Values.controller.crd.kinds }}
---

# If the controller is enabled and responsible for IguazioTenant, bind to the cluster-admin role 
# allowing it to do anything on the cluster

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "provazio.controller.name" . }}-iguaziotenant
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
subjects:
- kind: ServiceAccount
  name: {{ template "provazio.controller.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

{{- end }}

{{- if has "IguazioTenantAppServiceSet" .Values.controller.crd.kinds }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "provazio.controller.name" $ }}-namespace-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "provazio.name" $ }}
    chart: {{ template "provazio.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
subjects:
- kind: ServiceAccount
  name: {{ template "provazio.controller.name" $ }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "provazio.controller.name" $ }}-namespace-admin
  apiGroup: rbac.authorization.k8s.io

{{- if eq .Release.Namespace "default-tenant" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "provazio.controller.name" $ }}-admission-admin
  labels:
    app: {{ template "provazio.name" $ }}
    chart: {{ template "provazio.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
roleRef:
  kind: ClusterRole
  name: {{ template "provazio.controller.name" $ }}-admission-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "provazio.controller.name" $ }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: spark-operator-webhook
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- end }}

{{- end }}