image:
  repository: gcr.io/iguazio/metrics-server-exporter
  tag: unstable
  pullPolicy: IfNotPresent

container:
  port: 8000
  protocol: TCP
  scheme: HTTP
  path: /metrics
  healthzPath: /healthz

  logLevel: info

  handleGPUMetrics: false
  statusFieldSelector: status.phase=Running
  podListLimit: 100

service:
  port: 9104
  protocol: TCP

livenessProbe:
  failureThreshold: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 60

readinessProbe:
  failureThreshold: 3
  periodSeconds: 45
  successThreshold: 1
  timeoutSeconds: 30

startupProbe:
  failureThreshold: 10
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 10

## Deployment resources
resources: {}

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#  cpu: 100m
#  memory: 150Mi
# requests:
#  cpu: 100m
#  memory: 150Mi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## List of node taints to tolerate (requires Kubernetes >= 1.6)
tolerations: []
#  - key: "key"
#    operator: "Equal|Exists"
#    value: "value"
#    effect: "NoSchedule|PreferNoSchedule|NoExecute"

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

priorityClassName: ""
